---
- name: Update Kernel
  raw: >
    yum -y --exclude=libreoffice* --exclude=NetworkManager* --exclude=java* --exclude=nginx* --exclude=jenkins* update
    kernel kernel-devel kernel-headers kernel-tools kernel-tools-libs systemd btrfs-progs yum yum-plugin-fastestmirror
    python2-pip yum-utils kmod kmod-libs kexec-tools tzdata tzdata-java sudo rsyslog rpm pciutils iscsi-initiator-utils
    libiscsi device-mapper-multipath pam ntp ntpdate lvm2 logrotate kpatch kpartx git epel-release dhclient curl bash
    centos-release xfsdump xfsprogs open-vm-tools nmap-ncat polkit epel-release jq oniguruma
  register: update

- name: Check is reboot required
  command: needs-restarting -r
  register: reboot_required
  ignore_errors: yes
  changed_when: False

- name: Print reboot information
  debug:
    var: reboot_required.rc
    verbosity: 1

- name: Set reboot required fact
  set_fact:
    reboot_required: yes
  when: reboot_required.rc == 1

- name: Security check
  raw: yum --security check-update | grep -v " --"
  register: security_updates

